export const GET_EXCHANGE_BINANCE = 'GET_EXCHANGE_BINANCE';
export const GET_EXCHANGE_HUOBI = 'GET_EXCHANGE_HUOBI';
export const GET_HISTORY_INFO_HUOBI = 'GET_HISTORY_INFO_HUOBI';
export const SET_PAIRS = 'SET_PAIRS'; 
export const ERROR = 'ERROR';